CC = g++
SOURCE = checkFile.cpp parseCrates.cpp printCrates.cpp main.cpp
CFLAGS = -Wall

TARGET = day5

all: ${TARGET}

${TARGET}: ${SOURCE}
	${CC} ${CFLAGS} -o ${TARGET} ${SOURCE}

clean:
	${RM} ${TARGET}

